project:
  type: book
  output-dir: docs

book:
  title: "Learning Diary"
  author: "Hania Wojciak"
  date: "1/20/2026"
  chapters:
    - index.qmd
    #- intro.qmd
    - week1.qmd
    - week2.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - litera
      - brand
    css: styles.css
  pdf:
    documentclass: scrreprt

editor: visual

